#!/usr/bin/env python3
"""Export the knowledge base into content/<period>/info.md.

The history of each period is written and checked in a knowledge base kept outside this repo
(one Markdown file per period, named by the period id). This script copies its public part here:

    python3 scripts/export-knowledge.py <knowledge-dir> [--check]

Rules:
- Sections `## Private notes`, `## Open questions` and `## The banknotes` never leave the source
  (the gallery already shows the notes).
- Anything marked ⚠ (unverified) is dropped: the whole table row or list item, or the sentence
  in a paragraph. A table whose rows are all dropped is dropped too.
- Internal references (audit ids, wiki links) are removed.
- A guard refuses to write a file that still contains an unfinished or internal marker.
--check: write nothing, exit 1 if any info.md differs from what the export would produce.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PRIVATE = {"private notes", "open questions", "the banknotes"}
# Generic markers of unfinished or internal text. Extra words to refuse (one per line) can be kept
# in scripts/.guard-words, which is not tracked.
_EXTRA = ROOT / "scripts" / ".guard-words"
_WORDS = [re.escape(w.strip()) for w in (_EXTRA.read_text().splitlines() if _EXTRA.exists() else []) if w.strip()]
GUARD = re.compile("|".join([r"⚠", r"audit", r"#[A-Z]\d", r"\[\[", r"to source", r"unverified"] + _WORDS),
                   re.IGNORECASE)
HEADER = "<!-- Generated by scripts/export-knowledge.py. Edit the source, not this file. -->\n"


def clean(text):
    text = re.sub(r"\s*→\s*(\[\[[^\]]+\]\][,\s]*)+", "", text)       # "→ [[a]], [[b]]"
    text = re.sub(r"\[\[([^\]]+)\]\]", "", text)
    text = re.sub(r"\s*\((?:see )?audit #[A-Z]\d+(?:, #[A-Z]\d+)*\)", "", text)
    text = re.sub(r"\s*\(#[A-Z]\d+(?:, #[A-Z]\d+)*\)", "", text)
    return text


def drop_flagged_sentences(par):
    # split after . ! ? followed by space + capital/digit/**; keep sentences without ⚠
    parts = re.split(r"(?<=[.!?])\s+(?=[A-Z0-9*(])", par)
    kept = [p for p in parts if "⚠" not in p]
    return " ".join(kept)


def blocks(lines):
    """Group a section's lines into blocks: ('table', rows) · ('item', lines) · ('par', lines) · ('blank',)."""
    out, cur = [], None
    for ln in lines:
        if not ln.strip():
            cur = None
            out.append(("blank", []))
            continue
        if ln.startswith("|"):
            if not cur or cur[0] != "table":
                cur = ("table", [])
                out.append(cur)
            cur[1].append(ln)
        elif re.match(r"^\s*(?:[-*]|\d+\.)\s", ln) and not ln.startswith("  "):
            cur = ("item", [ln])
            out.append(cur)
        elif cur and cur[0] in ("item", "par"):
            cur[1].append(ln)
        else:
            cur = ("par", [ln])
            out.append(cur)
    return out


def render_section(lines):
    res = []
    for kind, body in blocks(lines):
        if kind == "blank":
            if res and res[-1] != "":
                res.append("")
        elif kind == "table":
            head, sep, rows = body[0], body[1], [r for r in body[2:] if "⚠" not in r]
            if rows:
                res += [head, sep] + rows
        elif kind == "item":
            if not any("⚠" in l for l in body):
                res += body
            else:
                item = " ".join(l.strip() for l in body)
                m = re.match(r"^((?:[-*]|\d+\.)\s+(?:\*\*[^*]+\*\*\s+—\s+)?)(.*)$", item)
                prefix, rest = m.group(1), m.group(2)
                rest = drop_flagged_sentences(rest)
                if rest.strip():
                    res.append(prefix + rest[0].lower() + rest[1:] if prefix.strip()[-1:] == "—" else prefix + rest)
        else:
            par = drop_flagged_sentences(" ".join(l.strip() for l in body))
            if par.strip():
                res.append(par)
    while res and res[-1] == "":
        res.pop()
    return res


def export_one(src_text):
    text = re.sub(r"\A---\n.*?\n---\n", "", src_text, flags=re.S)
    sections, title, cur = [], None, None
    for ln in text.splitlines():
        if ln.startswith("# ") and title is None:
            title = ln[2:].strip()
            continue
        m = re.match(r"^## (.+)", ln)
        if m:
            cur = [m.group(1).strip(), []]
            sections.append(cur)
        elif cur is not None:
            cur[1].append(ln)
    out = [HEADER]
    for name, body in sections:
        if name.lower() in PRIVATE:
            continue
        rendered = render_section([clean(l) for l in body])
        if not rendered:
            continue
        out.append(f"## {name}\n")
        out.append("\n".join(rendered) + "\n")
    md = "\n".join(out)
    if "H&K" in md:
        md += "\n*H&K = Hanke, S. H. & Krus, N. (2012), World Hyperinflations, Cato Working Paper no. 8.*\n"
    return md


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    check = "--check" in sys.argv
    if len(args) != 1:
        sys.exit(__doc__)
    src = Path(args[0])
    periods = json.loads((ROOT / "data" / "periods.json").read_text())["periods"]
    bad, changed, missing = [], [], []
    for p in periods:
        f = src / f"{p['id']}.md"
        if not f.exists():
            missing.append(p["id"])
            continue
        md = export_one(f.read_text())
        hits = sorted({m.group(0) for m in GUARD.finditer(md)})
        if hits:
            bad.append((p["id"], hits))
            continue
        dest = ROOT / "content" / p["id"] / "info.md"
        if not dest.exists() or dest.read_text() != md:
            changed.append(p["id"])
            if not check:
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(md)
    for pid, hits in bad:
        print(f"✗ {pid}: internal marker(s) {hits} — not written")
    for pid in missing:
        print(f"✗ {pid}: no source file")
    print(f"{'would change' if check else 'written'}: {len(changed)} · refused: {len(bad)} · missing: {len(missing)}")
    sys.exit(1 if bad or missing or (check and changed) else 0)


if __name__ == "__main__":
    main()
